Feat/pstb 5416
softwaregroup-bg/whitelist pull request #43
Opened 2022-01-05 16:44 UTC by NKozhuharski

2022-01-06 18:25 UTC, stoberov requested changes

2022-01-06 18:25 UTC, stoberov commented on impl/package.json
> +        "ut-hcm": "^0.1.1",
В този файл няма `ut-fcm`, което ме кара да мисля, че няма нужда от добавяне на `ut-hcm`. @NKozhuharski

2022-01-06 18:25 UTC, stoberov commented on ut/package.json
> +        "ut-hcm": "^0.1.1",
Може ли да спазим азбучния ред, т.е. да го преместим към ut-xxx модулите / близо до ut-fcm? @NKozhuharski

2022-01-06 20:07 UTC, NKozhuharski commented on impl/package.json
> +        "ut-hcm": "^0.1.1",
fixed

2022-01-06 20:07 UTC, NKozhuharski commented on ut/package.json
> +        "ut-hcm": "^0.1.1",
fixed

2022-01-07 10:17 UTC, stoberov approved these changes

2022-01-07 10:18 UTC, stoberov commented
@kalinkrustev - с уговорката, че Ники К ще продължи да ръчка по ut-hcm, мога ли да помоля за merge тук, за да го позволим като модул?

2022-01-07 14:04 UTC, merged